# Site wide configuration

title:            MLMogford
locale:           en_US
url:              https://mlmogford.dev
#url:

# Jekyll configuration

#permalink:   /:categories/:title/
permalink:   pretty
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Michael Mogford
  avatar: bio-photo.jpeg
  bio: "ML engineer and data scientist, working in th cloud"
  email: blog@mlmogford.com
  disqus-shortname:
  twitter: mlmogford
  facebook:
  google:
    analytics: 'UA-43220470-1'
  bing-verify:
  github: mlmogford
  #stackoverflow: 139637/custodio
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
